language: ruby
rvm:
      - 2.4.0
before_script:
  - bundle exec rake db:test:prepare

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search